orochi:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1

  joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2

  joint_3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_3

  joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_4

  joint_5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5

  joint_6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6

  joint_7_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_7

/gazebo_ros_control:
  pid_gains:
      joint_1: { p: 100.0, i: 0.01, d: 10.0}
      joint_2: { p: 100.0, i: 0.01, d: 10.0}
      joint_3: { p: 100.0, i: 0.01, d: 10.0}
      joint_4: { p: 100.0, i: 0.01, d: 10.0}
      joint_5: { p: 100.0, i: 0.01, d: 10.0}
      joint_6: { p: 100.0, i: 0.01, d: 10.0}
      joint_7: { p: 100.0, i: 0.01, d: 10.0}
